### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by klezm** [klezm/bloch#1]
- [ ] sin/cos plot for exp function (animated)
- [ ] animation for gate application (see: https://stolk.github.io/Blocher/)
- [ ] apply gate (should be optional. Maybe make a button `apply`) (see: https://javafxpert.github.io/grok-bloch/)
- [ ] auto update (use rxjs?)
- [ ] intuitive design...
